
import { Language, CalculationMethod, Madhab } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  [Language.ENGLISH]: {
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    qibla: 'Qibla',
    calendar: 'Calendar',
    settings: 'Settings',
    language: 'Language',
    method: 'Calculation Method',
    madhab: 'Asr Method',
    location: 'Location',
    adjust: 'Manual Adjustments',
    current: 'Current Prayer',
    next: 'Next Prayer',
    minutes: 'minutes',
    shafi: 'Shafi / Standard',
    hanafi: 'Hanafi',
    detectLocation: 'Auto-detect Location',
    calibration: 'Keep your phone flat for accuracy',
    distanceToMakkah: 'Distance to Makkah',
    privacyNote: 'Privacy First: No data ever leaves your device.',
    azanSettings: 'Azan Notifications',
    azanSound: 'Azan Style',
    azanPitch: 'Azan Pitch/Speed',
    notificationMode: 'Notification Mode',
    modeSound: 'Sound',
    modeVibrate: 'Vibrate',
    modeSilent: 'Silent',
    enableAzan: 'Enable Azan',
    testAzan: 'Test Notification',
    reminders: 'Prayer Reminders',
    reminderTime: 'Lead Time',
    reminderMsg: 'Upcoming prayer in {time} minutes',
    holidays: 'Islamic Events',
    hijriMonth: 'Hijri Month',
    islamicNewYear: 'Islamic New Year',
    ashura: 'Ashura',
    mawlid: 'Mawlid an-Nabi',
    israMiraj: 'Isra\' and Mi\'raj',
    midShaban: 'Mid-Sha\'ban',
    ramadanStart: 'Ramadan Start',
    laylatAlQadr: 'Laylat al-Qadr',
    eidAlFitr: 'Eid al-Fitr',
    arafah: 'Day of Arafah',
    eidAlAdha: 'Eid al-Adha'
  },
  [Language.BANGLA]: {
    fajr: 'ফজর',
    sunrise: 'সূর্যোদয়',
    dhuhr: 'যোহর',
    asr: 'আসর',
    maghrib: 'মাগরিব',
    isha: 'এশা',
    qibla: 'কিবলা',
    calendar: 'ক্যালেন্ডার',
    settings: 'সেটিংস',
    language: 'ভাষা',
    method: 'হিসাব পদ্ধতি',
    madhab: 'আসর পদ্ধতি',
    location: 'অবস্থান',
    adjust: 'ম্যানুয়াল সমন্বয়',
    current: 'চলমান সালাত',
    next: 'পরবর্তী সালাত',
    minutes: 'মিনিট',
    shafi: 'শাফি / সাধারণ',
    hanafi: 'হানাফি',
    detectLocation: 'অবস্থান সনাক্ত করুন',
    calibration: 'সঠিকতার জন্য ফোনটি সমতলে রাখুন',
    distanceToMakkah: 'মক্কা থেকে দূরত্ব',
    privacyNote: 'গোপনীয়তা আগে: কোনো তথ্যই আপনার ডিভাইসের বাইরে যায় না।',
    azanSettings: 'আযান বিজ্ঞপ্তি',
    azanSound: 'আযানের সুর',
    azanPitch: 'আযানের গতি/পিচ',
    notificationMode: 'বিজ্ঞপ্তি মোড',
    modeSound: 'শব্দ',
    modeVibrate: 'কম্পন',
    modeSilent: 'নিঃশব্দ',
    enableAzan: 'আযান চালু করুন',
    testAzan: 'টেস্ট নোটিফিকেশন',
    reminders: 'সালাতের রিমাইন্ডার',
    reminderTime: 'পূর্ববর্তী সময়',
    reminderMsg: '{time} মিনিট পর সালাত শুরু',
    holidays: 'ইসলামিক বিশেষ দিন',
    hijriMonth: 'হিজরি মাস',
    islamicNewYear: 'ইসলামী নববর্ষ',
    ashura: 'আশুরা',
    mawlid: 'ঈদে মিলাদুন্নবী',
    israMiraj: 'শবে মেরাজ',
    midShaban: 'শবে বরাত',
    ramadanStart: 'রমজান শুরু',
    laylatAlQadr: 'লাইলাতুল কদর',
    eidAlFitr: 'ঈদুল ফিতর',
    arafah: 'আরাফার দিন',
    eidAlAdha: 'ঈদুল আযহা'
  },
  [Language.ARABIC]: {
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    qibla: 'القبلة',
    calendar: 'التقويم',
    settings: 'الإعدادات',
    language: 'اللغة',
    method: 'طريقة الحساب',
    madhab: 'المذهب (العصر)',
    location: 'الموقع',
    adjust: 'تعديلات يدوية',
    current: 'الصلاة الحالية',
    next: 'الصلاة القادمة',
    minutes: 'دقائق',
    shafi: 'شافعي / قياسي',
    hanafi: 'حنفي',
    detectLocation: 'تحديد الموقع تلقائياً',
    calibration: 'أبقِ هاتفك مستوياً للدقة',
    distanceToMakkah: 'المسافة إلى مكة',
    privacyNote: 'الخصوصية أولاً: لا تخرج بياناتك عن جهازك أبداً.',
    azanSettings: 'إعدادات الأذان',
    azanSound: 'صوت الأذان',
    azanPitch: 'سرعة/طبقة الأذان',
    notificationMode: 'وضع التنبيه',
    modeSound: 'صوت',
    modeVibrate: 'اهتزاز',
    modeSilent: 'صامت',
    enableAzan: 'تفعيل الأذان',
    testAzan: 'تنبيه تجريبي',
    reminders: 'تنبيهات الصلاة',
    reminderTime: 'تنبيه قبل بـ',
    reminderMsg: 'الصلاة القادمة بعد {time} دقيقة',
    holidays: 'المناسبات الإسلامية',
    hijriMonth: 'الشهر الهجري',
    islamicNewYear: 'رأس السنة الهجرية',
    ashura: 'يوم عاشوراء',
    mawlid: 'المولد النبوي الشريف',
    israMiraj: 'الإسراء والمعراج',
    midShaban: 'ليلة النصف من شعبان',
    ramadanStart: 'بداية رمضان',
    laylatAlQadr: 'ليلة القدر',
    eidAlFitr: 'عيد الفطر',
    arafah: 'يوم عرفة',
    eidAlAdha: 'عيد الأضحى'
  },
  [Language.INDONESIAN]: {
    fajr: 'Subuh',
    sunrise: 'Terbit',
    dhuhr: 'Zuhur',
    asr: 'Asar',
    maghrib: 'Maghrib',
    isha: 'Isya',
    qibla: 'Kiblat',
    calendar: 'Kalender',
    settings: 'Pengaturan',
    language: 'Bahasa',
    method: 'Metode Perhitungan',
    madhab: 'Metode Asar',
    location: 'Lokasi',
    adjust: 'Penyesuaian Manual',
    current: 'Waktu Salat',
    next: 'Salat Berikutnya',
    minutes: 'menit',
    shafi: 'Syafii / Standar',
    hanafi: 'Hanafi',
    detectLocation: 'Deteksi Lokasi Otomatis',
    calibration: 'Pegang ponsel Anda dengan datar untuk akurasi',
    distanceToMakkah: 'Jarak ke Mekkah',
    privacyNote: 'Privasi Utama: Tidak ada data yang keluar dari perangkat Anda.',
    azanSettings: 'Pengaturan Azan',
    azanSound: 'Suara Azan',
    azanPitch: 'Kecepatan/Nada Azan',
    notificationMode: 'Mode Notifikasi',
    modeSound: 'Suara',
    modeVibrate: 'Getar',
    modeSilent: 'Senyap',
    enableAzan: 'Aktifkan Azan',
    testAzan: 'Tes Notifikasi',
    reminders: 'Pengingat Salat',
    reminderTime: 'Waktu Pengingat',
    reminderMsg: 'Waktu salat dalam {time} menit',
    holidays: 'Hari Besar Islam',
    hijriMonth: 'Bulan Hijriah',
    islamicNewYear: 'Tahun Baru Islam',
    ashura: 'Hari Asyura',
    mawlid: 'Maulid Nabi',
    israMiraj: 'Isra Mi\'raj',
    midShaban: 'Nisfu Sya\'ban',
    ramadanStart: 'Awal Ramadan',
    laylatAlQadr: 'Lailatul Qadar',
    eidAlFitr: 'Idul Fitri',
    arafah: 'Hari Arafah',
    eidAlAdha: 'Idul Adha'
  }
};

export const AZAN_SOUNDS = [
  { id: 'makkah', name: 'Makkah', url: 'https://www.islamcan.com/audio/adhan/azan1.mp3' },
  { id: 'madinah', name: 'Madinah', url: 'https://www.islamcan.com/audio/adhan/azan2.mp3' },
  { id: 'al-aqsa', name: 'Al-Aqsa', url: 'https://www.islamcan.com/audio/adhan/azan10.mp3' },
  { id: 'turkey', name: 'Turkey', url: 'https://www.islamcan.com/audio/adhan/azan14.mp3' },
  { id: 'egypt', name: 'Egypt', url: 'https://www.islamcan.com/audio/adhan/azan15.mp3' }
];

export const METHOD_NAMES: Record<CalculationMethod, string> = {
  [CalculationMethod.MWL]: 'Muslim World League',
  [CalculationMethod.ISNA]: 'Islamic Society of North America (ISNA)',
  [CalculationMethod.EGYPT]: 'Egyptian General Authority of Survey',
  [CalculationMethod.KARACHI]: 'University of Islamic Sciences, Karachi',
  [CalculationMethod.UMM_AL_QURA]: 'Umm al-Qura University, Makkah',
  [CalculationMethod.DUBAI]: 'Dubai',
  [CalculationMethod.KUWAIT]: 'Kuwait',
  [CalculationMethod.QATAR]: 'Qatar',
  [CalculationMethod.SINGAPORE]: 'MUIS (Singapore)',
  [CalculationMethod.TEHRAN]: 'Institute of Geophysics, Tehran',
  [CalculationMethod.TURKEY]: 'Turkey'
};

export const MAKKAH_COORDS = { lat: 21.4225, lon: 39.8262 };

export interface IslamicEvent {
  day: number;
  monthIndex: number; // 1-12
  translationKey: string;
}

export const ISLAMIC_EVENTS: IslamicEvent[] = [
  { day: 1, monthIndex: 1, translationKey: 'islamicNewYear' },
  { day: 10, monthIndex: 1, translationKey: 'ashura' },
  { day: 12, monthIndex: 3, translationKey: 'mawlid' },
  { day: 27, monthIndex: 7, translationKey: 'israMiraj' },
  { day: 15, monthIndex: 8, translationKey: 'midShaban' },
  { day: 1, monthIndex: 9, translationKey: 'ramadanStart' },
  { day: 27, monthIndex: 9, translationKey: 'laylatAlQadr' },
  { day: 1, monthIndex: 10, translationKey: 'eidAlFitr' },
  { day: 9, monthIndex: 12, translationKey: 'arafah' },
  { day: 10, monthIndex: 12, translationKey: 'eidAlAdha' },
];

export const HIJRI_MONTHS = [
  "Muharram", "Safar", "Rabi' al-awwal", "Rabi' al-thani",
  "Jumada al-ula", "Jumada al-akhira", "Rajab", "Sha'ban",
  "Ramadan", "Shawwal", "Dhu al-Qi'dah", "Dhu al-Hijjah"
];
